version: '3.8'

services:
  # =============================================================================
  # INFRASTRUCTURE SERVICES
  # =============================================================================
  
  # Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: crypto-bot-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
    networks:
      - crypto-bot-network
    restart: unless-stopped

  # Kafka broker
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: crypto-bot-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      # Performance optimizations for HFT
      KAFKA_NUM_NETWORK_THREADS: 8
      KAFKA_NUM_IO_THREADS: 16
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - crypto-bot-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Redis for caching and service registry
  redis:
    image: redis:7-alpine
    container_name: crypto-bot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - crypto-bot-network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped

  # =============================================================================
  # MONITORING SERVICES
  # =============================================================================

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: crypto-bot-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    networks:
      - crypto-bot-network
    restart: unless-stopped

  # AlertManager for handling alerts
  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: crypto-bot-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager:/etc/alertmanager
      - alertmanager-data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
    networks:
      - crypto-bot-network
    depends_on:
      - prometheus
    restart: unless-stopped

  # Grafana for visualization
  grafana:
    image: grafana/grafana:10.2.0
    container_name: crypto-bot-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - crypto-bot-network
    depends_on:
      - prometheus
    restart: unless-stopped

  # Streamlit app for ad-hoc analysis
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: crypto-bot-streamlit
    ports:
      - "8501:8501"
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
    volumes:
      - ./monitoring/streamlit:/app
    networks:
      - crypto-bot-network
    depends_on:
      - prometheus
    restart: unless-stopped

  # Node Exporter for system metrics
  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: crypto-bot-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - crypto-bot-network
    restart: unless-stopped

  # cAdvisor for container metrics
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: crypto-bot-cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - crypto-bot-network
    restart: unless-stopped

  # Kafka UI for monitoring
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: crypto-bot-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - crypto-bot-network
    restart: unless-stopped

  # =============================================================================
  # HFT MICROSERVICES
  # =============================================================================

  # Ingestion Service for Real-time Market Data
  ingestion-service:
    build:
      context: .
      dockerfile: services/ingestion/Dockerfile
    container_name: crypto-bot-ingestion
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"  # Metrics
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY:-}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY:-}
      - BINANCE_TESTNET=${BINANCE_TESTNET:-true}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC_ORDER_BOOK=order_book_updates
      - KAFKA_TOPIC_TRADE_TICKS=trade-ticks
      - KAFKA_CLIENT_ID=ingestion-service
      - SYMBOLS=${SYMBOLS:-BTCUSDT,ETHUSDT,ADAUSDT}
      - ORDER_BOOK_DEPTH=${ORDER_BOOK_DEPTH:-20}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FORMAT=json
      - METRICS_PORT=8000
      - SERVICE_NAME=ingestion
      - SERVICE_VERSION=1.0.0
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - crypto-bot-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Kalman Filter Service for Dynamic Hedge Ratio Calculation
  kalman-filter-service:
    build:
      context: .
      dockerfile: services/kalman_filter/Dockerfile
    container_name: crypto-bot-kalman-filter
    depends_on:
      kafka:
        condition: service_healthy
      ingestion-service:
        condition: service_started
    ports:
      - "8001:8001"  # Metrics
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_CONSUMER_TOPIC=trade-ticks
      - KAFKA_PRODUCER_TOPIC=signals-hedge-ratio
      - KAFKA_CONSUMER_GROUP=kalman-filter-service
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FORMAT=json
      - METRICS_PORT=8001
      - SERVICE_NAME=kalman-filter
      - SERVICE_VERSION=1.0.0
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - crypto-bot-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # GARCH Volatility Service for Dynamic Threshold Calculation
  garch-volatility-service:
    build:
      context: .
      dockerfile: services/garch_model/Dockerfile
    container_name: crypto-bot-garch-volatility
    depends_on:
      kafka:
        condition: service_healthy
      kalman-filter-service:
        condition: service_started
    ports:
      - "8002:8002"  # Metrics
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_CONSUMER_TOPIC=spread-data
      - KAFKA_PRODUCER_TOPIC=signals-thresholds
      - KAFKA_CONSUMER_GROUP=garch-volatility-service
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FORMAT=json
      - METRICS_PORT=8002
      - SERVICE_NAME=garch-model
      - SERVICE_VERSION=1.0.0
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - crypto-bot-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Execution Service for Trading Strategy Orchestration
  execution-service:
    build:
      context: .
      dockerfile: services/execution/Dockerfile
    container_name: crypto-bot-execution
    depends_on:
      kafka:
        condition: service_healthy
      garch-volatility-service:
        condition: service_started
      kalman-filter-service:
        condition: service_started
    ports:
      - "8003:8003"  # Metrics
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_CONSUMER_TOPICS=order_book_updates,signals-hedge-ratio,signals-thresholds,trading-halt
      - KAFKA_PRODUCER_TOPICS=spread-data,trade-orders
      - KAFKA_CONSUMER_GROUP=execution-service
      - BINANCE_API_KEY=${BINANCE_API_KEY:-}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY:-}
      - BINANCE_TESTNET=${BINANCE_TESTNET:-true}
      - DATABASE_URL=sqlite:///data/trading.db
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FORMAT=json
      - METRICS_PORT=8003
      - SERVICE_NAME=execution
      - SERVICE_VERSION=1.0.0
      # Risk management settings
      - MAX_POSITION_SIZE=${MAX_POSITION_SIZE:-10000}
      - MAX_DAILY_LOSS=${MAX_DAILY_LOSS:-5000}
      - MAX_DRAWDOWN_PERCENT=${MAX_DRAWDOWN_PERCENT:-10}
      - KELLY_LOOKBACK_DAYS=${KELLY_LOOKBACK_DAYS:-30}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - crypto-bot-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Risk Manager Service for Changepoint Detection
  risk-manager-service:
    build:
      context: .
      dockerfile: services/risk_manager/Dockerfile
    container_name: crypto-bot-risk-manager
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      execution-service:
        condition: service_started
    ports:
      - "8004:8004"  # Metrics
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_SPREAD_TOPIC=spread-data
      - KAFKA_HALT_TOPIC=trading-halt
      - KAFKA_RECOVERY_TOPIC=trading-recovery
      - KAFKA_CONSUMER_GROUP=risk-manager-group
      - BOCD_HAZARD_RATE=0.004  # 1/250
      - BOCD_MAX_RUN_LENGTH=500
      - BOCD_MIN_OBSERVATIONS=10
      - USE_ADAPTIVE_BOCD=true
      - WARNING_THRESHOLD=0.5
      - HALT_THRESHOLD=0.7
      - CRITICAL_THRESHOLD=0.9
      - MIN_HALT_DURATION_MINUTES=5
      - MAX_HALT_DURATION_HOURS=2
      - RECOVERY_PROBABILITY_THRESHOLD=0.2
      - METRICS_PORT=8004
      - REDIS_URL=redis://redis:6379
      - SERVICE_NAME=risk-manager
      - SERVICE_VERSION=1.0.0
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FORMAT=json
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - crypto-bot-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Orchestrator Service for EVOP Framework
  orchestrator-service:
    build:
      context: .
      dockerfile: services/orchestrator/Dockerfile
    container_name: crypto-bot-orchestrator
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      execution-service:
        condition: service_started
      kalman-filter-service:
        condition: service_started
      garch-volatility-service:
        condition: service_started
      risk-manager-service:
        condition: service_started
    ports:
      - "8005:8005"  # API and metrics
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - REDIS_URL=redis://redis:6379
      - ORCHESTRATOR_PORT=8005
      - SERVICE_NAME=orchestrator
      - SERVICE_VERSION=1.0.0
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FORMAT=json
      # EVOP Configuration
      - EVOP_MAX_CHALLENGERS=${EVOP_MAX_CHALLENGERS:-3}
      - EVOP_CHALLENGER_CAPITAL_FRACTION=${EVOP_CHALLENGER_CAPITAL_FRACTION:-0.2}
      - EVOP_MIN_EVALUATION_DAYS=${EVOP_MIN_EVALUATION_DAYS:-7}
      - EVOP_MAX_EVALUATION_DAYS=${EVOP_MAX_EVALUATION_DAYS:-30}
      - EVOP_MIN_TRADES=${EVOP_MIN_TRADES:-10}
      - EVOP_CONFIDENCE_LEVEL=${EVOP_CONFIDENCE_LEVEL:-0.95}
      - EVOP_MIN_SHARPE_IMPROVEMENT=${EVOP_MIN_SHARPE_IMPROVEMENT:-0.1}
      - EVOP_MIN_CALMAR_IMPROVEMENT=${EVOP_MIN_CALMAR_IMPROVEMENT:-0.1}
      - EVOP_MAX_DRAWDOWN_TOLERANCE=${EVOP_MAX_DRAWDOWN_TOLERANCE:-0.15}
      - EVOP_MAX_TOTAL_ALLOCATION=${EVOP_MAX_TOTAL_ALLOCATION:-1.0}
      - EVOP_EMERGENCY_STOP_DRAWDOWN=${EVOP_EMERGENCY_STOP_DRAWDOWN:-0.25}
      - EVOP_MUTATION_RATE=${EVOP_MUTATION_RATE:-0.1}
      - EVOP_MUTATION_STD=${EVOP_MUTATION_STD:-0.05}
      - EVOP_EVALUATION_FREQUENCY=${EVOP_EVALUATION_FREQUENCY:-6}
      - EVOP_RESTART_ON_FAILURE=${EVOP_RESTART_ON_FAILURE:-true}
      # Champion Strategy Configuration
      - CHAMPION_INITIAL_CAPITAL=${CHAMPION_INITIAL_CAPITAL:-100000.0}
      - CHAMPION_ENTRY_Z_SCORE=${CHAMPION_ENTRY_Z_SCORE:-2.0}
      - CHAMPION_EXIT_Z_SCORE=${CHAMPION_EXIT_Z_SCORE:-0.5}
      - CHAMPION_STOP_LOSS_Z_SCORE=${CHAMPION_STOP_LOSS_Z_SCORE:-4.0}
      - CHAMPION_MAX_POSITION_SIZE=${CHAMPION_MAX_POSITION_SIZE:-10000.0}
      - CHAMPION_MAX_DRAWDOWN_PERCENT=${CHAMPION_MAX_DRAWDOWN_PERCENT:-10.0}
      - CHAMPION_MAX_DAILY_LOSS=${CHAMPION_MAX_DAILY_LOSS:-5000.0}
      - CHAMPION_KELLY_FRACTION=${CHAMPION_KELLY_FRACTION:-0.25}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - crypto-bot-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.5'
        reservations:
          memory: 1G
          cpus: '1.0'

# =============================================================================
# VOLUMES
# =============================================================================
volumes:
  zookeeper-data:
    driver: local
  zookeeper-logs:
    driver: local
  kafka-data:
    driver: local
  redis-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  alertmanager-data:
    driver: local

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  crypto-bot-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16