apiVersion: v2
name: ingestion
description: Market Data Ingestion Service for HFT Crypto Bot
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - trading
  - ingestion
  - market-data
  - websocket
maintainers:
  - name: HFT Development Team
    email: dev@hft-crypto-bot.com
