# Default values for ingestion service
replicaCount: 2

image:
  repository: hft-crypto-bot-ingestion
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "2000m"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      selectPolicy: Max

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 2

env:
  WEBSOCKET_CONNECTIONS: "10"
  KAFKA_BATCH_SIZE: "100"
  SYMBOLS: "BTCUSDT,ETHUSDT,ADAUSDT,BNBUSDT,SOLUSDT"
  SERVICE_NAME: "ingestion"
  METRICS_PORT: "8000"

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8000"
  prometheus.io/path: "/metrics"

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
