apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onchain-data.fullname" . }}
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    {{- include "onchain-data.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "onchain-data.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "onchain-data.selectorLabels" . | nindent 8 }}
        app: onchain-data-service
    spec:
      {{- if .Values.global.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      {{- if .Values.initContainers.enabled }}
      initContainers:
        - name: data-init
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
          image: "{{ .Values.global.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              echo "Initializing data directory..."
              mkdir -p /app/data/models
              mkdir -p /app/data/cache
              echo "Data initialization complete"
          volumeMounts:
            - name: data-storage
              mountPath: {{ .Values.persistence.mountPath }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
          image: "{{ .Values.global.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- include "hft-crypto-bot.commonEnv" . | nindent 12 }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.externalSecrets.enabled }}
            # API keys from external secrets
            - name: GLASSNODE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecrets.secretName }}
                  key: glassnode-api-key
            - name: CRYPTOQUANT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecrets.secretName }}
                  key: cryptoquant-api-key
            {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "hft-crypto-bot.volumeMounts" . | nindent 12 }}
            {{- if .Values.persistence.enabled }}
            - name: data-storage
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
      volumes:
        {{- include "hft-crypto-bot.volumes" . | nindent 8 }}
        {{- if .Values.persistence.enabled }}
        - name: data-storage
          persistentVolumeClaim:
            claimName: {{ include "onchain-data.fullname" . }}-pvc
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
