apiVersion: v1
kind: Secret
metadata:
  name: hft-secrets
  namespace: hft-staging
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  # echo -n "your_api_key" | base64
  BINANCE_API_KEY: eW91cl9hcGlfa2V5X2hlcmU=  # your_api_key_here
  BINANCE_SECRET_KEY: eW91cl9zZWNyZXRfa2V5X2hlcmU=  # your_secret_key_here
  
  # Slack webhook for notifications
  SLACK_WEBHOOK_URL: eW91cl9zbGFja193ZWJob29rX3VybA==  # your_slack_webhook_url
  
  # Database credentials (if using external DB)
  DATABASE_URL: c3FsaXRlOi8vL2RhdGEvdHJhZGluZ19zdGFnaW5nLmRi  # sqlite:///data/trading_staging.db
  
  # Registry credentials (if needed)
  DOCKER_REGISTRY_TOKEN: eW91cl9yZWdpc3RyeV90b2tlbg==  # your_registry_token
