# Staging environment values for HFT Crypto Bot

# Global overrides for staging
global:
  namespace: hft-staging
  environment: staging
  tag: "latest"
  
  # Reduced resources for staging
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

# Infrastructure components with reduced resources
infrastructure:
  enabled: true
  
  kafka:
    enabled: true
    replicaCount: 1
    persistence:
      enabled: false  # Use emptyDir for staging
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
    config:
      numPartitions: 1  # Fewer partitions for staging
      logRetentionHours: 24  # 1 day retention
      
  zookeeper:
    enabled: true
    replicaCount: 1
    persistence:
      enabled: false
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
        
  redis:
    enabled: true
    replicaCount: 1
    persistence:
      enabled: false
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"

# Core services with staging configuration
services:
  ingestion:
    enabled: true
    replicaCount: 1
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3  # Reduced for staging
      targetCPUUtilizationPercentage: 60  # More aggressive scaling
    env:
      WEBSOCKET_CONNECTIONS: "5"  # Fewer connections
      KAFKA_BATCH_SIZE: "50"
      
  kalmanFilter:
    enabled: true
    replicaCount: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 70
    env:
      KALMAN_BATCH_SIZE: "25"
      KALMAN_UPDATE_FREQ: "2000"
      
  garchModel:
    enabled: true
    replicaCount: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
    autoscaling:
      enabled: false  # Disable for staging simplicity
    env:
      GARCH_WINDOW: "100"  # Smaller window
      GARCH_UPDATE_FREQ: "10000"
      
  execution:
    enabled: true
    replicaCount: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 70
    env:
      MAX_POSITION_SIZE: "5000"  # Reduced for staging
      MAX_DAILY_LOSS: "1000"
      ENABLE_PAPER_TRADING: "true"  # Always paper trading in staging
      
  riskManager:
    enabled: true
    replicaCount: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    autoscaling:
      enabled: false  # Single instance for staging
    env:
      BOCD_HAZARD_RATE: "0.01"  # More sensitive for testing
      WARNING_THRESHOLD: "0.3"
      HALT_THRESHOLD: "0.5"
      
  orchestrator:
    enabled: true
    replicaCount: 1
    resources:
      requests:
        memory: "1Gi"
        cpu: "750m"
      limits:
        memory: "4Gi"
        cpu: "3000m"
    autoscaling:
      enabled: false  # Single instance
    env:
      EVOP_MAX_CHALLENGERS: "2"  # Fewer challengers
      EVOP_CHALLENGER_CAPITAL_FRACTION: "0.2"
      EVOP_MIN_EVALUATION_DAYS: "1"  # Faster evaluation
      EVOP_CONFIDENCE_LEVEL: "0.8"  # Lower confidence for testing
      EVOP_EVALUATION_FREQUENCY: "2"  # Every 2 hours
      CHAMPION_INITIAL_CAPITAL: "10000.0"  # Smaller capital

# Monitoring with reduced resources
monitoring:
  enabled: true
  
  prometheus:
    enabled: true
    replicaCount: 1
    persistence:
      enabled: false  # Use emptyDir for staging
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
    retention: 3d  # Shorter retention
    
  grafana:
    enabled: true
    replicaCount: 1
    persistence:
      enabled: false
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    adminPassword: "staging123"
    
  alertmanager:
    enabled: true
    replicaCount: 1
    persistence:
      enabled: false
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"

# Configuration for staging
config:
  trading:
    symbols: "BTCUSDT,ETHUSDT"  # Fewer symbols for staging
    binanceTestnet: true  # Always use testnet
    maxDrawdownPercent: 5  # Stricter limits for testing
    
  logging:
    level: DEBUG  # More verbose logging
    format: json

# Pod disruption budgets disabled for staging
podDisruptionBudget:
  enabled: false

# Network policies disabled for staging simplicity
networkPolicy:
  enabled: false
